name: custombank
description: A custom banking application
publish_to: 'none'
version: 1.0.1+3  # Increment both version name and code

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  provider: ^6.1.1
  uuid: ^4.2.1
  shimmer: ^2.0.0
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6

flutter:
  uses-material-design: true
  assets:
    - assets/chase_logo.png
    - assets/bankofamerica_logo.png
    - assets/capitalone_logo.png
    - assets/citibank_logo.png
    - assets/wells_fargo_logo.png
    - assets/usbank_logo.png
    - assets/pnc_logo.png
    - assets/tdbank_logo.png
    - assets/ally_logo.png
    - assets/truist_logo.png
    - assets/mastercard_logo.png
    - assets/visa_logo.png
    - assets/legal/privacy_policy.md
    - assets/legal/terms_of_service.md
    - assets/custombank_logo.png